print("=-=-=-=-=RECIPE-=-=-=-=-=")
print("-=-=-=-=-=-=-=-=-=-=-=-=-")
print("|        LASAGNA        |")
print("|-----------------------|")
print("|Ingredients:           |")
print("|-Box of lasagna noodles|")
print("|-Some kind of tomatoes |")
print("|-Some meats            |")
print("|-Spicy seasonings      |")
print("|                       |")
print("|Steps:                 |")
print("|-Boil noodles part way |")
print("|-Heat up everything    |")
print("|-Burn something        |")
print("|-Panic                 |")
print("|-Hope it isnt bad      |")
print("|-Magic                 |")
print("|-Somehow it's good     |")
print("|-Panic some more       |")
print("|-DONE!                 |")
print("|-Enjoy!                |")
print("|~~~~~~~~~~~~~~~~~~~~~~~|")
print("|???????????????????????|")



