print("-------------------------------------------------")
print("                MY DAILY SCHEDULE                ")
print("-------------------------------------------------")
print("6:30 am - Wake up")
print("6:45 am - Leave for work")
print("7:00 am - Arrive at work")
print("7:45 am - Start to be productive")
print("8:00 am - Leave for job Site")
print("8:30 am - Arrive at job asite and begin work")
print("3:00 pm - Head back to shop")
print("3:30 pm - Get back to shop and bitch about work🫠")
print("4:00 pm - Head back home")
print("4:15 pm - Get back home and start studying👌")
print("9:00 pm - Go to sleep and start again 😴")
print("-------------------------------------------------")