print("======================")
print("------ ABOUT ME ------")
print("======================")
print("|Name:  Connor       |")
print("|Age:   35           |")
print("|City:  Omaha        |")
print("|Hobby: Video Games  |")
print("======================")
print("===Learning Python!===")
print("======================")